## Kaggle sourced data on hotels and the reviews from the customers

In [ ]:
#importing libraries
import pandas as pd
import numpy as np

In [ ]:
#importing libraries and setting display options
import time
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

from sklearn.preprocessing import LabelEncoder
pd.set_option('display.width', 1000)

In [ ]:
print("Loading data file now, this could take a while depending on file size")
start = time.time()
# df is 'DataFrame'
df = pd.read_csv('/Users/stephenkeyen/NLP projects/maxxing/Hotel_Reviews.csv')
end = time.time()
print("Loading took " + str(round(end - start, 2)) + " seconds")

Loading data file now, this could take a while depending on file size
Loading took 1.68 seconds

In [ ]:
df.head(10) #first 10 rows of the data frame

                                       Hotel_Address  Additional_Number_of_Scoring Review_Date  Average_Score   Hotel_Name Reviewer_Nationality                                    Negative_Review  Review_Total_Negative_Word_Counts  Total_Number_of_Reviews                                    Positive_Review  Review_Total_Positive_Word_Counts  Total_Number_of_Reviews_Reviewer_Has_Given  Reviewer_Score                                               Tags days_since_review        lat       lng
0   s Gravesandestraat 55 Oost 1092 AA Amsterdam ...                           194    8/3/2017            7.7  Hotel Arena              Russia    I am so angry that i made this post available...                                397                     1403   Only the park outside of the hotel was beauti...                                 11                                           7             2.9  [' Leisure trip ', ' Couple ', ' Duplex Double...            0 days  52.360576  4.915968
1   s Gravesandestraat 55 Oost 1092 AA Amsterdam ...                           194    8/3/2017            7.7  Hotel Arena             Ireland                                         No Negative                                  0                     1403   No real complaints the hotel was great great ...                                105                                           7             7.5  [' Leisure trip ', ' Couple ', ' Duplex Double...            0 days  52.360576  4.915968
2   s Gravesandestraat 55 Oost 1092 AA Amsterdam ...                           194   7/31/2017            7.7  Hotel Arena           Australia    Rooms are nice but for elderly a bit difficul...                                 42                     1403   Location was good and staff were ok It is cut...                                 21                                           9             7.1  [' Leisure trip ', ' Family with young childre...            3 days  52.360576  4.915968
3   s Gravesandestraat 55 Oost 1092 AA Amsterdam ...                           194   7/31/2017            7.7  Hotel Arena      United Kingdom    My room was dirty and I was afraid to walk ba...                                210                     1403   Great location in nice surroundings the bar a...                                 26                                           1             3.8  [' Leisure trip ', ' Solo traveler ', ' Duplex...            3 days  52.360576  4.915968
4   s Gravesandestraat 55 Oost 1092 AA Amsterdam ...                           194   7/24/2017            7.7  Hotel Arena         New Zealand    You When I booked with your company on line y...                                140                     1403    Amazing location and building Romantic setting                                   8                                           3             6.7  [' Leisure trip ', ' Couple ', ' Suite ', ' St...           10 days  52.360576  4.915968
5   s Gravesandestraat 55 Oost 1092 AA Amsterdam ...                           194   7/24/2017            7.7  Hotel Arena              Poland    Backyard of the hotel is total mess shouldn t...                                 17                     1403   Good restaurant with modern design great chil...                                 20                                           1             6.7  [' Leisure trip ', ' Group ', ' Duplex Double ...           10 days  52.360576  4.915968
6   s Gravesandestraat 55 Oost 1092 AA Amsterdam ...                           194   7/17/2017            7.7  Hotel Arena      United Kingdom    Cleaner did not change our sheet and duvet ev...                                 33                     1403   The room is spacious and bright The hotel is ...                                 18                                           6             4.6  [' Leisure trip ', ' Group ', ' Duplex Twin Ro...           17 days  52.360576  4.915968
7   s Gravesandestraat 55 Oost 1092 AA Amsterdam ...                           194   7/17/2017            7.7  Hotel Arena      United Kingdom    Apart from the price for the brekfast Everyth...                                 11                     1403   Good location Set in a lovely park friendly s...                                 19                                           1            10.0  [' Leisure trip ', ' Couple ', ' Duplex Double...           17 days  52.360576  4.915968
8   s Gravesandestraat 55 Oost 1092 AA Amsterdam ...                           194    7/9/2017            7.7  Hotel Arena             Belgium    Even though the pictures show very clean room...                                 34                     1403                                        No Positive                                  0                                           3             6.5  [' Leisure trip ', ' Couple ', ' Duplex Double...           25 days  52.360576  4.915968
9   s Gravesandestraat 55 Oost 1092 AA Amsterdam ...                           194    7/8/2017            7.7  Hotel Arena              Norway    The aircondition makes so much noise and its ...                                 15                     1403   The room was big enough and the bed is good T...                                 50                                           1             7.9  [' Leisure trip ', ' Couple ', ' Large King Ro...           26 days  52.360576  4.915968

In [ ]:
#importing custom function to describe the dataset
import sys

if '/Users/stephenkeyen/Downloads/Functions 2' not in sys.path:
  sys.path.append('/Users/stephenkeyen/Downloads/Functions 2')

In [7]:
import function as fun

In [8]:
#custom function to describe the dataset
print(fun.metadata(df))

                                   column_name datatype  missing_percent  unique         mean          std        min          25%          50%          75%           max
0                                Hotel_Address      str             0.00    1493          NaN          NaN        NaN          NaN          NaN          NaN           NaN
1                 Additional_Number_of_Scoring    int64             0.00     480   498.081836   500.538467   1.000000   169.000000   341.000000   660.000000   2682.000000
2                                  Review_Date      str             0.00     731          NaN          NaN        NaN          NaN          NaN          NaN           NaN
3                                Average_Score  float64             0.00      34     8.397487     0.548048   5.200000     8.100000     8.400000     8.800000      9.800000
4                                   Hotel_Name      str             0.00    1492          NaN          NaN        NaN          NaN          NaN          NaN           NaN
5                         Reviewer_Nationality      str             0.00     227          NaN          NaN        NaN          NaN          NaN          NaN           NaN
6                              Negative_Review      str             0.00  330011          NaN          NaN        NaN          NaN          NaN          NaN           NaN
7            Review_Total_Negative_Word_Counts    int64             0.00     402    18.539450    29.690831   0.000000     2.000000     9.000000    23.000000    408.000000
8                      Total_Number_of_Reviews    int64             0.00    1142  2743.743944  2317.464868  43.000000  1161.000000  2134.000000  3613.000000  16670.000000
9                              Positive_Review      str             0.00  412601          NaN          NaN        NaN          NaN          NaN          NaN           NaN
10           Review_Total_Positive_Word_Counts    int64             0.00     365    17.776458    21.804185   0.000000     5.000000    11.000000    22.000000    395.000000
11  Total_Number_of_Reviews_Reviewer_Has_Given    int64             0.00     198     7.166001    11.040228   1.000000     1.000000     3.000000     8.000000    355.000000
12                              Reviewer_Score  float64             0.00      37     8.395077     1.637856   2.500000     7.500000     8.800000     9.600000     10.000000
13                                        Tags      str             0.00   55242          NaN          NaN        NaN          NaN          NaN          NaN           NaN
14                           days_since_review      str             0.00     731          NaN          NaN        NaN          NaN          NaN          NaN           NaN
15                                         lat  float64             0.63    1472    49.442439     3.466325  41.328376    48.214662    51.499981    51.516288     52.400181
16                                         lng  float64             0.63    1472     2.823803     4.579425  -0.369758    -0.143372     0.010607     4.834443     16.429233

In [ ]:
df.shape # df rows and columns count

(515738, 17)

In [10]:
nationality_freq = df["Reviewer_Nationality"].value_counts()

In [11]:
# What reviewer nationality is the most common in the dataset?
print("The highest frequency reviewer nationality is " + str(nationality_freq.index[0]))

The highest frequency reviewer nationality is  United Kingdom

In [12]:
nationality_freq.shape

(227,)

In [13]:
# What is the top 10 most common nationalities and their frequencies?
print("The top 10 highest frequency reviewer nationalities are:")
print(nationality_freq[0:10].to_string())

The top 10 highest frequency reviewer nationalities are:
Reviewer_Nationality
United Kingdom               245246
United States of America      35437
Australia                     21686
Ireland                       14827
United Arab Emirates          10235
Saudi Arabia                   8951
Netherlands                    8772
Switzerland                    8678
Germany                        7941
Canada                         7894

In [14]:
# What was the most frequently reviewed hotel for the top 10 nationalities - print the hotel and number of reviews
for nat in nationality_freq.head(10).index:

    nat_df = df[df["Reviewer_Nationality"] == nat]

    freq = nat_df["Hotel_Name"].value_counts()

    if not freq.empty:
        print(
            f"The most reviewed hotel for {nat} was "
            f"{freq.index[0]} with {freq.iloc[0]} reviews."
        )

The most reviewed hotel for  United Kingdom  was Britannia International Hotel Canary Wharf with 3833 reviews.
The most reviewed hotel for  United States of America  was Hotel Esther a with 423 reviews.
The most reviewed hotel for  Australia  was Park Plaza Westminster Bridge London with 167 reviews.
The most reviewed hotel for  Ireland  was Copthorne Tara Hotel London Kensington with 239 reviews.
The most reviewed hotel for  United Arab Emirates  was Millennium Hotel London Knightsbridge with 129 reviews.
The most reviewed hotel for  Saudi Arabia  was The Cumberland A Guoman Hotel with 142 reviews.
The most reviewed hotel for  Netherlands  was Jaz Amsterdam with 97 reviews.
The most reviewed hotel for  Switzerland  was Hotel Da Vinci with 97 reviews.
The most reviewed hotel for  Germany  was Hotel Da Vinci with 86 reviews.
The most reviewed hotel for  Canada  was St James Court A Taj Hotel London with 61 reviews.

In [ ]:
# running analysis on a select set of columns of importance to the analysis of the dataset.
selected_cols = [
    'Hotel_Name',
    'Reviewer_Score',
    'Total_Number_of_Reviews', 
    'lat', 
    'lng'
]

hotel_freqs_df = df[selected_cols].copy()

In [16]:
hotel_freqs_df.head(5)

    Hotel_Name  Reviewer_Score  Total_Number_of_Reviews        lat       lng
0  Hotel Arena             2.9                     1403  52.360576  4.915968
1  Hotel Arena             7.5                     1403  52.360576  4.915968
2  Hotel Arena             7.1                     1403  52.360576  4.915968
3  Hotel Arena             3.8                     1403  52.360576  4.915968
4  Hotel Arena             6.7                     1403  52.360576  4.915968

In [ ]:
#Creating a unique identifier for each hotel based on name and location (latitude and longitude)
# to avoid confusion between hotels with similar names in different locations. 
# This will help in accurately analyzing the data related to each specific hotel.
hotel_freqs_df['Hotel_ID'] = (
    hotel_freqs_df['Hotel_Name'].astype(str)
    + "_"
    + hotel_freqs_df['lat'].round(3).astype(str)
    + "_"
    + hotel_freqs_df['lng'].round(3).astype(str)
)

In [ ]:
#Calculating the total number of reviews found for each hotel by grouping the data by 'Hotel_ID' and
# counting the occurrences of each unique hotel identifier. 
# This will provide insight into how many reviews are associated with each specific hotel in the dataset.
# No guarantee to validate 'Total_Nuumber_of_Reviews' column in original dataset,
# so we will calculate our own 'Total_Reviews_Found' column 
# based on the actual number of reviews found in the dataset for each hotel.
hotel_freqs_df['Total_Reviews_Found'] = (
    hotel_freqs_df.groupby('Hotel_ID')
    .Hotel_ID
    .transform('size')
)

In [ ]:
#dropping duplicates based on 'Hotel_ID'.
hotel_summary = hotel_freqs_df.drop_duplicates(
    subset=['Hotel_ID']
).copy()

In [20]:
hotel_summary.head(10)

                            Hotel_Name  Reviewer_Score  Total_Number_of_Reviews        lat       lng                                        Hotel_ID  Total_Reviews_Found
0                          Hotel Arena             2.9                     1403  52.360576  4.915968                        Hotel Arena_52.361_4.916                405.0
405                   K K Hotel George             9.6                     1831  51.491888 -0.194971                  K K Hotel George_51.492_-0.195                566.0
971            Apex Temple Court Hotel             9.2                     2619  51.513734 -0.108751           Apex Temple Court Hotel_51.514_-0.109               1037.0
2008  The Park Grand London Paddington             8.3                     4380  51.514218 -0.180903  The Park Grand London Paddington_51.514_-0.181               1770.0
3778               Monhotel Lounge SPA             9.2                      171  48.874348  2.289733                 Monhotel Lounge SPA_48.874_2.29                 35.0
3813                Kube Hotel Ice Bar             3.3                      197  48.886570  2.358833                 Kube Hotel Ice Bar_48.887_2.359                 19.0
3832              The Principal London             7.1                     3150  51.522622 -0.125160              The Principal London_51.523_-0.125               1425.0
5257     Park Plaza County Hall London             5.0                     6117  51.501400 -0.116009     Park Plaza County Hall London_51.501_-0.116               2223.0
7480                       One Aldwych             5.4                      259  51.511783 -0.119417                       One Aldwych_51.512_-0.119                136.0
7616                   Splendid Etoile             7.5                      486  48.874707  2.293676                    Splendid Etoile_48.875_2.294                127.0

In [21]:
hotel_summary.shape

(1478, 7)

In [22]:
print(fun.metadata(hotel_summary))

               column_name datatype  missing_percent  unique         mean          std        min         25%         50%          75%           max
0               Hotel_Name      str             0.00    1476          NaN          NaN        NaN         NaN         NaN          NaN           NaN
1           Reviewer_Score  float64             0.00      28     8.314682     1.720581   2.500000    7.500000    8.800000     9.600000     10.000000
2  Total_Number_of_Reviews    int64             0.00    1132  1297.539242  1374.745242  43.000000  421.250000  866.500000  1677.000000  16670.000000
3                      lat  float64             0.07    1472    48.339336     3.415746  41.328376   45.533137   48.866856    51.504716     52.400181
4                      lng  float64             0.07    1472     3.966140     4.922368  -0.369758   -0.071492    2.307724     4.885964     16.429233
5                 Hotel_ID      str             0.07    1477          NaN          NaN        NaN         NaN         NaN          NaN           NaN
6      Total_Reviews_Found  float64             0.07     661   346.966825   442.975908   8.000000   90.000000  194.000000   428.000000   4789.000000

In [25]:
hotel_summary.dropna(inplace=True)

In [ ]:
# data summary after dropping rows with missing values and preparating for analysis
print(fun.metadata(hotel_summary))

               column_name datatype  missing_percent  unique         mean          std        min         25%         50%          75%           max
0               Hotel_Name      str              0.0    1475          NaN          NaN        NaN         NaN         NaN          NaN           NaN
1           Reviewer_Score  float64              0.0      28     8.313541     1.720605   2.500000    7.500000    8.800000     9.600000     10.000000
2  Total_Number_of_Reviews    int64              0.0    1132  1298.162492  1375.001969  43.000000  422.000000  867.000000  1679.000000  16670.000000
3                      lat  float64              0.0    1472    48.339336     3.415746  41.328376   45.533137   48.866856    51.504716     52.400181
4                      lng  float64              0.0    1472     3.966140     4.922368  -0.369758   -0.071492    2.307724     4.885964     16.429233
5                 Hotel_ID      str              0.0    1477          NaN          NaN        NaN         NaN         NaN          NaN           NaN
6      Total_Reviews_Found  float64              0.0     661   346.966825   442.975908   8.000000   90.000000  194.000000   428.000000   4789.000000

In [ ]:
# Saving new data file with calculated columns
print("Saving results to Hotel_Summary.csv")
hotel_summary.to_csv(r'/Users/stephenkeyen/NLP projects/Hotel reviews/Hotel_Summary.csv', index = False)

Saving results to Hotel_Reviews_Filtered.csv

In [ ]:
# define a function that takes a row and performs some calculation with it
def get_difference_review_avg(row):
  return row["Average_Score"] - row["Calc_Average_Score"]

df['Calc_Average_Score'] = round(df.groupby('Hotel_Name').Reviewer_Score.transform('mean'), 1)

# Add a new column with the difference between the two average scores
df["Average_Score_Difference"] = df.apply(get_difference_review_avg, axis = 1)

# Create a df without all the duplicates of Hotel_Name (so only 1 row per hotel)
review_scores_df = df.drop_duplicates(subset = ["Hotel_Name"])

# Sort the dataframe to find the lowest and highest average score difference
review_scores_df = review_scores_df.sort_values(by=["Average_Score_Difference"])

display(review_scores_df[["Average_Score_Difference", "Average_Score", "Calc_Average_Score", "Hotel_Name"]])

In [ ]:

start = time.time()
no_negative_reviews = sum(df.Negative_Review == "No Negative")
print("Number of No Negative reviews: " + str(no_negative_reviews))

no_positive_reviews = sum(df["Positive_Review"] == "No Positive")
print("Number of No Positive reviews: " + str(no_positive_reviews))

both_no_reviews = sum((df.Negative_Review == "No Negative") & (df.Positive_Review == "No Positive"))
print("Number of both No Negative and No Positive reviews: " + str(both_no_reviews))

end = time.time()
print("Sum took " + str(round(end - start, 2)) + " seconds")

Number of No Negative reviews: 127890
Number of No Positive reviews: 35946
Number of both No Negative and No Positive reviews: 127
Sum took 0.17 seconds

## After exploration it was found only the following cities and countries were in the data set -
Amsterdam, Netherlands

Barcelona, Spain

London, United Kingdom

Milan, Italy

Paris, France

Vienna, Austria

In [32]:
def replace_address(row):
    if "Netherlands" in row["Hotel_Address"]:
        return "Amsterdam, Netherlands"
    elif "Barcelona" in row["Hotel_Address"]:
        return "Barcelona, Spain"
    elif "United Kingdom" in row["Hotel_Address"]:
        return "London, United Kingdom"
    elif "Milan" in row["Hotel_Address"]:        
        return "Milan, Italy"
    elif "France" in row["Hotel_Address"]:
        return "Paris, France"
    elif "Vienna" in row["Hotel_Address"]:
        return "Vienna, Austria" 

# Replace all the addresses with a shortened, more useful form
df["Hotel_Address"] = df.apply(replace_address, axis = 1)
# The sum of the value_counts() should add up to the total number of reviews
print(df["Hotel_Address"].value_counts())

Hotel_Address
London, United Kingdom    262301
Barcelona, Spain           60149
Paris, France              59928
Amsterdam, Netherlands     57214
Vienna, Austria            38939
Milan, Italy               37207
Name: count, dtype: int64

In [33]:
display(df.groupby("Hotel_Address").agg({"Hotel_Name": "nunique"}))

                        Hotel_Name
Hotel_Address
Amsterdam, Netherlands         105
Barcelona, Spain               211
London, United Kingdom         400
Milan, Italy                   162
Paris, France                  458
Vienna, Austria                158

In [35]:
# Saving new data file with calculated columns
print("Saving results to Hotel_Reviews_Filtered.csv")
df.to_csv(r'/Users/stephenkeyen/NLP projects/Hotel reviews/Hotel_Reviews_Filtered.csv', index = False)

Saving results to Hotel_Reviews_Filtered.csv